package indexany.gui;

import indexany.GuiColumn;
import indexany.Index;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

public class CreateIndexDialog extends javax.swing.JDialog {

    /**
     * Creates new form CreateIndexDialog
     */
    public CreateIndexDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listmodel = new DefaultListModel<>();
        index = new Index("");
        colList.setModel(listmodel);
        lastPrimaryColIndex = -1;
        lastPrimaryColText = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editLayoutButton = new javax.swing.JButton();
        titleText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        colNameLabel = new javax.swing.JLabel();
        colNameText = new javax.swing.JTextField();
        colTypeLabel = new javax.swing.JLabel();
        colTypeComboBox = new javax.swing.JComboBox();
        colRequiredCheckbox = new javax.swing.JCheckBox();
        colUniqueCheckbox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        addColButton = new javax.swing.JButton();
        defaultValLabel = new javax.swing.JLabel();
        defaultValText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        colList = new javax.swing.JList();
        doneButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Index");

        editLayoutButton.setText("Edit Columns Layout..");
        editLayoutButton.setEnabled(false);
        editLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLayoutButtonActionPerformed(evt);
            }
        });

        titleText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        titleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleTextKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Column Properties"));

        colNameLabel.setLabelFor(colNameText);
        colNameLabel.setText("Name");

        colTypeLabel.setLabelFor(colTypeComboBox);
        colTypeLabel.setText("Type");

        colTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Text", "Link", "Links", "Email", "Emails", "Date", "Integer" }));

        colRequiredCheckbox.setText("Required");

        colUniqueCheckbox.setText("Unique");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        addColButton.setText("Add Column");
        addColButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addColButtonActionPerformed(evt);
            }
        });

        defaultValLabel.setLabelFor(defaultValText);
        defaultValLabel.setText("Default Value");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(defaultValLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultValText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(colTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(colNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colNameText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colRequiredCheckbox)
                            .addComponent(colUniqueCheckbox))))
                .addContainerGap())
            .addComponent(addColButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(colNameLabel)
                                .addComponent(colNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(colRequiredCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(colTypeLabel)
                                .addComponent(colTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(colUniqueCheckbox)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultValText)
                    .addComponent(defaultValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addColButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        colList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        colList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                colListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(colList);

        doneButton.setText("Done!");
        doneButton.setEnabled(false);
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        titleLabel.setLabelFor(titleText);
        titleLabel.setText("Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editLayoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton)
                    .addComponent(editLayoutButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTextKeyReleased
        index.setTitle(titleText.getText());
        if (titleText.getText().replaceAll("\\s", "").isEmpty()) {
            doneButton.setEnabled(false);
        } else if (!listmodel.isEmpty()) {
            doneButton.setEnabled(true);
        }
    }//GEN-LAST:event_titleTextKeyReleased

    private void addColButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addColButtonActionPerformed
        if (colNameText.getText().isEmpty() || index.hasColumn(colNameText.getText())) {
            return;
        }
        GuiColumn col = new GuiColumn();
        col.setName(colNameText.getText());
        col.setType(colTypeComboBox.getSelectedIndex());
        col.setRequired(colRequiredCheckbox.isSelected());
        col.setUnique(colUniqueCheckbox.isSelected());
        col.setDefaultValue(defaultValText.getText());
        index.addColumn(col);
        listmodel.addElement(col.getName() + ", " + colTypeComboBox.getSelectedItem() + ", " + (col.isRequired() ? "Required" : "non-Req") + ", " + (col.isUnique() ? "Unique" : "non-Uniq") + ", " + col.getDefaultValue());
        if (!titleText.getText().isEmpty()) {
            doneButton.setEnabled(true);
        }
        editLayoutButton.setEnabled(true);
    }//GEN-LAST:event_addColButtonActionPerformed

    private void colListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colListMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3) {
            JPopupMenu menu = new JPopupMenu();
            menu.add(new JMenuItem("Set Primary")).addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!colList.isSelectionEmpty()) {
                        if (lastPrimaryColIndex > -1) {
                            listmodel.set(lastPrimaryColIndex, lastPrimaryColText);
                        }
                        index.setPrimaryColumnName(colList.getSelectedValue().toString().split(",", 2)[0]);
                        lastPrimaryColIndex = colList.getSelectedIndex();
                        lastPrimaryColText = colList.getSelectedValue().toString();
                        listmodel.set(lastPrimaryColIndex, "<html><b>" + lastPrimaryColText + "</b></html>");
                    }
                }
            });
            menu.add(new JMenuItem("Remove")).addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (!colList.isSelectionEmpty()) {
                        index.removeColumn(colList.getSelectedValue().toString().split(",", 2)[0]);
                        listmodel.remove(colList.getSelectedIndex());
                        if (listmodel.isEmpty()) {
                            doneButton.setEnabled(false);
                            editLayoutButton.setEnabled(false);
                        } else if (!titleText.getText().replaceAll("\\s", "").isEmpty()) {
                            doneButton.setEnabled(true);
                        }
                    }
                }
            });
            menu.show(colList, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_colListMouseReleased

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void editLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLayoutButtonActionPerformed
        EditColumnsLayoutDialog asdf = new EditColumnsLayoutDialog(null, true, index.getColumns());
        asdf.setVisible(true);
    }//GEN-LAST:event_editLayoutButtonActionPerformed

    public Index getIndex() {
        if (index.getTitle().isEmpty()) {
            return null;
        }
        if (index.getColumnsCount() == 0) {
            return null;
        }
        return index;
    }

    {
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateIndexDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateIndexDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateIndexDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateIndexDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                CreateIndexDialog dialog = new CreateIndexDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addColButton;
    private javax.swing.JList colList;
    private javax.swing.JLabel colNameLabel;
    private javax.swing.JTextField colNameText;
    private javax.swing.JCheckBox colRequiredCheckbox;
    private javax.swing.JComboBox colTypeComboBox;
    private javax.swing.JLabel colTypeLabel;
    private javax.swing.JCheckBox colUniqueCheckbox;
    private javax.swing.JLabel defaultValLabel;
    private javax.swing.JTextField defaultValText;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editLayoutButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<String> listmodel;
    private Index index;
    private int lastPrimaryColIndex;
    private String lastPrimaryColText;
}
